# Generated by Django 3.0.7 on 2020-06-26 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Secret Word')),
                ('category', models.CharField(choices=[('movies', 'Movies'), ('celebrities', 'Celebreties'), ('places', 'Places')], max_length=20, verbose_name='Category')),
                ('sub_category', models.CharField(max_length=50, verbose_name='Sub-category')),
                ('last_used', models.DateTimeField(verbose_name='Last used')),
                ('used_count', models.DateTimeField(verbose_name='Used count')),
                ('correct_guesses', models.IntegerField(verbose_name='Correct guesses')),
            ],
        ),
        migrations.CreateModel(
            name='GamesPlayed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guessed_letters', models.CharField(max_length=72, verbose_name='Guessed letters')),
                ('guesses', models.IntegerField(verbose_name='Number of guesses')),
                ('won', models.BooleanField(verbose_name='Won')),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='Started')),
                ('end_time', models.DateTimeField(auto_now_add=True, verbose_name='Ended')),
                ('feedback', models.IntegerField(verbose_name='Feedback')),
                ('secret_word_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.WordMaster')),
            ],
        ),
    ]
