# Generated by Django 3.0.7 on 2020-06-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmaster',
            name='correct_guesses',
            field=models.IntegerField(blank=True, verbose_name='Correct guesses'),
        ),
        migrations.AlterField(
            model_name='wordmaster',
            name='last_used',
            field=models.DateTimeField(blank=True, verbose_name='Last used'),
        ),
        migrations.AlterField(
            model_name='wordmaster',
            name='used_count',
            field=models.DateTimeField(blank=True, verbose_name='Used count'),
        ),
    ]
