# Generated by Django 3.0.7 on 2020-06-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200626_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesplayed',
            old_name='secret_word_id',
            new_name='word_id',
        ),
        migrations.AlterField(
            model_name='gamesplayed',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ended'),
        ),
        migrations.AlterField(
            model_name='gamesplayed',
            name='feedback',
            field=models.IntegerField(null=True, verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='gamesplayed',
            name='guessed_letters',
            field=models.CharField(max_length=72, null=True, verbose_name='Guessed letters'),
        ),
        migrations.AlterField(
            model_name='gamesplayed',
            name='guesses',
            field=models.IntegerField(null=True, verbose_name='Number of guesses'),
        ),
        migrations.AlterField(
            model_name='gamesplayed',
            name='start_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Started'),
        ),
        migrations.AlterField(
            model_name='gamesplayed',
            name='won',
            field=models.BooleanField(null=True, verbose_name='Won'),
        ),
    ]
