# Generated by Django 3.0.7 on 2020-06-28 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200626_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesplayed',
            old_name='word_id',
            new_name='word_master',
        ),
    ]
